import CombinatorialContracts

-- Every ledger declaration must exist in the all-module aggregate.
#check CombinatorialContracts.EndpointRegression.empty_ground_optimalValue
#check CombinatorialContracts.EqualRevenue.approxSupply_card_explicit
#check CombinatorialContracts.EqualRevenue.approxSupply_card_le_of_critical_gaps
#check CombinatorialContracts.EqualRevenue.binaryIndex_injective
#check CombinatorialContracts.EqualRevenue.binaryIndex_surjective
#check CombinatorialContracts.EqualRevenue.critical_isResponse
#check CombinatorialContracts.EqualRevenue.harmonic_binary_bounds
#check CombinatorialContracts.EqualRevenue.proposition10
#check CombinatorialContracts.FiniteEnvelope.exists_partition
#check CombinatorialContracts.FiniteEnvelope.exists_partition_max_slope
#check CombinatorialContracts.LowerBounds.accuracy_binary_bounds
#check CombinatorialContracts.LowerBounds.compiledPointProgram_probes_le
#check CombinatorialContracts.LowerBounds.corollary3_exact_worst_instance
#check CombinatorialContracts.LowerBounds.decodeNat_correct
#check CombinatorialContracts.LowerBounds.exists_finite_program_of_termination
#check CombinatorialContracts.LowerBounds.exists_hidden_expected_supply_ge_average_ennreal
#check CombinatorialContracts.LowerBounds.hard_family
#check CombinatorialContracts.LowerBounds.randomized_high_accuracy_query_bound_lintegral
#check CombinatorialContracts.LowerBounds.randomized_strategy_program_exact
#check CombinatorialContracts.LowerBounds.theorem8_worst_instance
#check CombinatorialContracts.LowerBounds.unique_optimal_contract
#check CombinatorialContracts.OracleIdentification.adaptive_identification
#check CombinatorialContracts.OracleIdentification.randomized_identification_lintegral
#check CombinatorialContracts.OracleProgram
#check CombinatorialContracts.OracleProgram.algorithm1Program_counts
#check CombinatorialContracts.OracleProgram.robustProgram_counts
#check CombinatorialContracts.OracleRun.output_mem
#check CombinatorialContracts.Paper.theorem1
#check CombinatorialContracts.Paper.theorem1_empty
#check CombinatorialContracts.Paper.theorem2
#check CombinatorialContracts.Paper.theorem2_empty
#check CombinatorialContracts.Paper.theorem7
#check CombinatorialContracts.Paper.theorem7_empty
#check CombinatorialContracts.SupplyProgram
#check CombinatorialContracts.SupplyProgram.algorithm_counts
#check CombinatorialContracts.Tightness.Bundle.normalized_localization_ratio
#check CombinatorialContracts.Tightness.proposition9_i
#check CombinatorialContracts.Tightness.proposition9_ii
#check CombinatorialContracts.approximate_clipped_welfare_estimate
#check CombinatorialContracts.approximate_oracle_robustness
#check CombinatorialContracts.approximate_undershoot_payoff
#check CombinatorialContracts.empty_ground_zero
#check CombinatorialContracts.eventually_exponential_supply_lower_bound_ennreal
#check CombinatorialContracts.exists_optimum
#check CombinatorialContracts.exists_response
#check CombinatorialContracts.exists_reward_anchor
#check CombinatorialContracts.finite_first_appearance_bound
#check CombinatorialContracts.geometric_cover_of_width
#check CombinatorialContracts.leastGridSteps_add_one_bound
#check CombinatorialContracts.leastGridSteps_minimal
#check CombinatorialContracts.leastGridSteps_one
#check CombinatorialContracts.leastGridSteps_spec
#check CombinatorialContracts.principal_le_welfare
#check CombinatorialContracts.principal_nonneg
#check CombinatorialContracts.response_reward_mono
#check CombinatorialContracts.response_reward_monotone
#check CombinatorialContracts.reward_anchored_scale_of_optimal_response
#check CombinatorialContracts.robust_source_grid_cover
#check CombinatorialContracts.scaled_optimalValue
#check CombinatorialContracts.scaled_response_iff
#check CombinatorialContracts.scaled_welfare
#check CombinatorialContracts.shifted_contract_valid
#check CombinatorialContracts.subadditive_le_sum_singletons
#check CombinatorialContracts.supplyResponse_iff_response
#check CombinatorialContracts.welfare_eq_zero_iff_optimalValue_eq_zero
#check CombinatorialContracts.welfare_profit_comparison

-- Full headline axiom closures; these have only the source model/oracle premises.
#print axioms CombinatorialContracts.Paper.theorem1
#print axioms CombinatorialContracts.Paper.theorem2
#print axioms CombinatorialContracts.Paper.theorem7
#print axioms CombinatorialContracts.reward_anchored_scale_of_optimal_response
#print axioms CombinatorialContracts.LowerBounds.theorem8_worst_instance
#print axioms CombinatorialContracts.LowerBounds.corollary3_exact_worst_instance
#print axioms CombinatorialContracts.Tightness.proposition9_i
#print axioms CombinatorialContracts.Tightness.proposition9_ii
#print axioms CombinatorialContracts.EqualRevenue.proposition10
